### ISSUE TITLE
Crashing after Force Quit

### ISSUE THREAD

**Issue by Swader** [Planetable/Planet#270]
I regularly have to Force Quit the app on my M1 because the Quit button is and remains greyed out (never become available). Sometimes, it fails to start back up, crashing immediately on load.

<img width="1039" alt="image" src="https://github.com/Planetable/Planet/assets/1430603/01fa84c0-22b8-46cc-866a-afb780d1ef75">

<img width="986" alt="image" src="https://github.com/Planetable/Planet/assets/1430603/163d7dd4-8e26-483c-85fd-1c79a2420f7c">

**Comment by livid** [comment]
When this happens, it is usually caused by a stuck IPFS process.

You can force-quit the IPFS process by locating it in the Activity Monitor.

<img width="1061" alt="Screenshot 2023-09-03 at 6 08 59 PM" src="https://github.com/Planetable/Planet/assets/11427/ba1c3698-a9c6-4b3a-bd26-80fb7943839f">

The IPFS process can become stuck when the network condition changes drastically.

**Comment by Swader** [comment]
Perfect, killing IPFS helped. Thanks!
